"""Import the root MySQL demo SQL into an isolated PostgreSQL schema.

Reads the repository's Inspection_System1.sql and Sample_Input.sql files.
Set ROOT_SQL_DATABASE_URL or enter the connection URL at the hidden prompt.
"""

import getpass
import os
from datetime import datetime, timezone
from pathlib import Path

import psycopg


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_FILE = PROJECT_ROOT / "Inspection_System1.sql"
SAMPLE_DATA_FILE = PROJECT_ROOT / "Sample_Input.sql"

POSTGRES_SCHEMA = """
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS inspection_system;

CREATE TABLE IF NOT EXISTS inspection_system.ngos (
    ngo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngo_name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS inspection_system.inspectors (
    inspector_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    assigned_ngo_id BIGINT REFERENCES inspection_system.ngos(ngo_id),
    UNIQUE (name, assigned_ngo_id)
);

CREATE TABLE IF NOT EXISTS inspection_system.inspections (
    inspection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspector_id BIGINT NOT NULL REFERENCES inspection_system.inspectors(inspector_id),
    ngo_id BIGINT NOT NULL REFERENCES inspection_system.ngos(ngo_id),
    inspection_datetime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inspection_status TEXT NOT NULL CHECK (
        inspection_status IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled')
    ),
    latitude NUMERIC(10, 8) NOT NULL,
    longitude NUMERIC(11, 8) NOT NULL,
    location geometry(Point, 4326) NOT NULL,
    inspector_reached_location BOOLEAN NOT NULL DEFAULT FALSE,
    inspection_completed BOOLEAN NOT NULL DEFAULT FALSE,
    evidence_timestamp TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS inspection_system.inspection_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT NOT NULL
        REFERENCES inspection_system.inspections(inspection_id) ON DELETE CASCADE,
    evidence_type TEXT NOT NULL CHECK (evidence_type IN ('Photo', 'Video')),
    file_url VARCHAR(500) NOT NULL,
    evidence_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    UNIQUE (inspection_id, evidence_type, file_url)
);

CREATE INDEX IF NOT EXISTS inspections_location_gix
    ON inspection_system.inspections USING GIST (location);
"""


def validate_source_files() -> None:
    if not SCHEMA_FILE.is_file() or not SAMPLE_DATA_FILE.is_file():
        raise FileNotFoundError(
            "Expected root SQL files Inspection_System1.sql and Sample_Input.sql."
        )
    schema_sql = SCHEMA_FILE.read_text(encoding="utf-8")
    sample_sql = SAMPLE_DATA_FILE.read_text(encoding="utf-8")
    required_tables = (
        "CREATE TABLE ngos",
        "CREATE TABLE inspectors",
        "CREATE TABLE inspections",
        "CREATE TABLE inspection_evidence",
    )
    if not all(table in schema_sql for table in required_tables):
        raise ValueError("The root inspection schema differs from the supported MySQL source format.")
    required_sample_values = (
        "Green Earth Foundation",
        "Rahul Sharma",
        "Green Earth",
        "Rahul",
        "Completed",
        "30.70464900",
        "76.71787300",
        "uploads/inspection1/photo1.jpg",
    )
    if not all(value in sample_sql for value in required_sample_values):
        raise ValueError("Sample_Input.sql differs from the supported sample data.")


def import_root_sql(database_url: str) -> None:
    validate_source_files()
    latitude = 30.704649
    longitude = 76.717873
    now = datetime.now(timezone.utc)

    with psycopg.connect(database_url, connect_timeout=15) as connection:
        for statement in POSTGRES_SCHEMA.split(";"):
            if statement.strip():
                connection.execute(statement)
        ngo_id = connection.execute(
            """INSERT INTO inspection_system.ngos (ngo_name)
            VALUES (%s)
            ON CONFLICT (ngo_name) DO UPDATE SET ngo_name = EXCLUDED.ngo_name
            RETURNING ngo_id""",
            ("Green Earth Foundation",),
        ).fetchone()[0]
        inspector_id = connection.execute(
            """INSERT INTO inspection_system.inspectors (name, assigned_ngo_id)
            VALUES (%s, %s)
            ON CONFLICT (name, assigned_ngo_id)
            DO UPDATE SET name = EXCLUDED.name
            RETURNING inspector_id""",
            ("Rahul Sharma", ngo_id),
        ).fetchone()[0]
        inspection_id = connection.execute(
            """SELECT inspection_id
            FROM inspection_system.inspections
            WHERE inspector_id = %s AND ngo_id = %s
                AND inspection_status = 'Completed'
                AND latitude = %s AND longitude = %s
                AND inspector_reached_location = TRUE
                AND inspection_completed = TRUE
            ORDER BY inspection_id
            LIMIT 1""",
            (inspector_id, ngo_id, latitude, longitude),
        ).fetchone()
        if inspection_id is None:
            inspection_id = connection.execute(
                """INSERT INTO inspection_system.inspections (
                    inspector_id, ngo_id, inspection_datetime, inspection_status,
                    latitude, longitude, location, inspector_reached_location,
                    inspection_completed, evidence_timestamp
                ) VALUES (
                    %s, %s, %s, 'Completed', %s, %s,
                    ST_SetSRID(ST_MakePoint(%s, %s), 4326),
                    TRUE, TRUE, %s
                )
                RETURNING inspection_id""",
                (
                    inspector_id,
                    ngo_id,
                    now,
                    latitude,
                    longitude,
                    longitude,
                    latitude,
                    now,
                ),
            ).fetchone()
        connection.execute(
            """INSERT INTO inspection_system.inspection_evidence (
                inspection_id, evidence_type, file_url, evidence_timestamp,
                latitude, longitude
            ) VALUES (%s, 'Photo', %s, %s, %s, %s)
            ON CONFLICT (inspection_id, evidence_type, file_url) DO NOTHING""",
            (
                inspection_id[0],
                "uploads/inspection1/photo1.jpg",
                now,
                latitude,
                longitude,
            ),
        )


def main() -> None:
    validate_source_files()
    database_url = os.getenv("ROOT_SQL_DATABASE_URL", "").strip()
    if not database_url:
        database_url = getpass.getpass("PostgreSQL connection URL (input hidden): ").strip()
    if not database_url:
        raise ValueError("A PostgreSQL connection URL is required.")
    import_root_sql(database_url)
    print("Root SQL schema and sample data imported into PostgreSQL schema inspection_system.")


if __name__ == "__main__":
    main()
